#!/bin/bash
set -e

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker buildx create --use --name xbuilder
docker buildx build --platform linux/amd64,linux/arm/v7 -t test-chopsticks .